name: on-commit
on:
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  bump_tag:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      # GitHub Action: https://github.com/marketplace/actions/github-tag-bump
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        DEFAULT_BRANCH: main
        WITH_V: false

  changelog:
    needs: bump_tag
    runs-on: ubuntu-latest
    name: Generate and Commit Changelog

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.6
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
        git push
          
  notification:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: ${{ secrets.MATRIX_SERVER }}
          message: |
            "${{ github.repository }}": changes to source directory detected<br />
            **Tekton pipeline triggered**<br />
            commit message: **${{ github.event.head_commit.message }}** <br />
            contributor: **${{ github.actor }}** <br />
            commit sha: **${{ github.sha }}** <br />
            commit history: **[link](https://github.com/${{ github.repository }}/commits/main)** <br />
            Pipeline: **[link](https://console-openshift-console.apps.ocp.michard.cc/pipelines/ns/build-environment)** <br />